# Generated by Django 2.1 on 2018-08-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0028_merge_20180816_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='landmark_image',
            field=models.ImageField(blank=True, null=True, upload_to='location_images'),
        ),
    ]
